---
gcrKeyPath: /root/bm-gcr.json
sshPrivateKeyPath: /root/.ssh/id_rsa
gkeConnectAgentServiceAccountKeyPath: /root/bm-gcr.json
gkeConnectRegisterServiceAccountKeyPath: /root/bm-gcr.json
cloudOperationsServiceAccountKeyPath: /root/bm-gcr.json
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-{CLUSTER_ID}
---
apiVersion: baremetal.cluster.gke.io/v1
kind: Cluster
metadata:
  name: {CLUSTER_ID}
  namespace: cluster-{CLUSTER_ID}
spec:
  type: hybrid
  anthosBareMetalVersion: 1.12.0
  gkeConnect:
    projectID: {PROJECT_ID}
  controlPlane:
    nodePoolSpec:
      clusterName: {CLUSTER_ID}
      nodes:
      - address: 10.200.8.3
      - address: 10.200.8.4
      - address: 10.200.8.5
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 172.26.232.0/24
  loadBalancer:
    mode: bundled
    ports:
      controlPlaneLBPort: 443
    vips:
      controlPlaneVIP: 10.200.8.49
      ingressVIP: 10.200.8.50
    addressPools:
    - name: pool1
      addresses:
      - 10.200.8.50-10.200.8.70
  clusterOperations:
    # might need to be this location
    location: {REGION}
    projectID: {PROJECT_ID}
  storage:
    lvpNodeMounts:
      path: /mnt/localpv-disk
      storageClassName: node-disk
    lvpShare:
      numPVUnderSharedPath: 5
      path: /mnt/localpv-share
      storageClassName: standard
---
apiVersion: baremetal.cluster.gke.io/v1
kind: NodePool
metadata:
  name: node-pool-1
  namespace: cluster-{CLUSTER_ID}
spec:
  clusterName: {CLUSTER_ID}
  nodes:
  - address: 10.200.8.6
  - address: 10.200.8.7